name: Deploy Indra Arianggi's Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          bun install

      - name: Build
        run: |
          bun run build

      - name: Upload to VPS (temporary dir)
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "out/*"
          target: "/home/${{ secrets.VPS_USERNAME }}/tmp-deploy"
          rm: true
          strip_components: 1

      - name: Move to /var/www with sudo
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/indraarianggi-site
            sudo mkdir -p /var/www/indraarianggi-site
            sudo mv /home/${{ secrets.VPS_USERNAME }}/tmp-deploy/* /var/www/indraarianggi-site
